---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: component-compass-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: component-compass-secret
    creationPolicy: Owner
  data:
    - secretKey: AUTH_SECRET
      remoteRef:
        key: /component-compass/auth-secret
    - secretKey: CC_TOKEN
      remoteRef:
        key: /component-compass/cc-token
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: /component-compass/oidc-client-secret
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /component-compass/postgres-password
