---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: component-compass-secret
spec:
  refreshInterval: 5m
  secretStoreRef:
    name: infisical
    kind: ClusterSecretStore
  target:
    name: component-compass-secret
    creationPolicy: Owner
  data:
    - secretKey: AUTH_SECRET
      remoteRef:
        key: /component-compass/AUTH_SECRET
    - secretKey: CLI_TOKEN_SECRET
      remoteRef:
        key: /component-compass/CLI_TOKEN_SECRET
    - secretKey: COMPASS_CI_UPLOAD_TOKEN
      remoteRef:
        key: /component-compass/COMPASS_CI_UPLOAD_TOKEN
    - secretKey: OIDC_CLIENT_SECRET
      remoteRef:
        key: /component-compass/OIDC_CLIENT_SECRET
    - secretKey: POSTGRES_PASSWORD
      remoteRef:
        key: /component-compass/POSTGRES_PASSWORD
